-- Database Setup Script for Train Booking System
-- Run this script in your MySQL database to create the required tables

-- Create database if it doesn't exist
CREATE DATABASE IF NOT EXISTS reservation;
USE reservation;

-- Create CUSTOMER table for user registration
CREATE TABLE IF NOT EXISTS CUSTOMER (
    MAILID VARCHAR(100) PRIMARY KEY,
    PWORD VARCHAR(100) NOT NULL,
    FNAME VARCHAR(50) NOT NULL,
    LNAME VARCHAR(50) NOT NULL,
    ADDR VARCHAR(200) NOT NULL,
    PHNO BIGINT NOT NULL
);

-- Create ADMIN table for admin users
CREATE TABLE IF NOT EXISTS ADMIN (
    MAILID VARCHAR(100) PRIMARY KEY,
    PWORD VARCHAR(100) NOT NULL,
    FNAME VARCHAR(50) NOT NULL,
    LNAME VARCHAR(50) NOT NULL,
    ADDR VARCHAR(200) NOT NULL,
    PHNO BIGINT NOT NULL
);

-- Create TRAINS table for train information
CREATE TABLE IF NOT EXISTS TRAINS (
    TRAIN_NO BIGINT PRIMARY KEY,
    TRAIN_NAME VARCHAR(100) NOT NULL,
    FROM_STN VARCHAR(100) NOT NULL,
    TO_STN VARCHAR(100) NOT NULL,
    AVAILABLE_SEATS INT NOT NULL,
    FARE DECIMAL(10,2) NOT NULL,
    TRAIN_DATE DATE NOT NULL
);

-- Create BOOKING_HISTORY table for booking records
CREATE TABLE IF NOT EXISTS BOOKING_HISTORY (
    BOOKING_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MAILID VARCHAR(100) NOT NULL,
    TRAIN_NO BIGINT NOT NULL,
    BOOKING_DATE DATE NOT NULL,
    TRAVEL_DATE DATE NOT NULL,
    PASSENGER_NAME VARCHAR(100) NOT NULL,
    PASSENGER_AGE INT NOT NULL,
    PASSENGER_GENDER VARCHAR(10) NOT NULL,
    SEAT_NO VARCHAR(10) NOT NULL,
    FARE DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (MAILID) REFERENCES CUSTOMER(MAILID),
    FOREIGN KEY (TRAIN_NO) REFERENCES TRAINS(TRAIN_NO)
);

-- Insert default admin user (password: admin123)
INSERT INTO ADMIN (MAILID, PWORD, FNAME, LNAME, ADDR, PHNO) 
VALUES ('admin@train.com', 'admin123', 'Admin', 'User', 'Admin Address', 1234567890)
ON DUPLICATE KEY UPDATE MAILID=MAILID;

-- Insert sample train data
INSERT INTO TRAINS (TRAIN_NO, TRAIN_NAME, FROM_STN, TO_STN, AVAILABLE_SEATS, FARE, TRAIN_DATE) VALUES
(12345, 'Express Train', 'Mumbai', 'Delhi', 50, 1500.00, '2024-01-15'),
(12346, 'Super Fast', 'Delhi', 'Kolkata', 40, 1200.00, '2024-01-16'),
(12347, 'Local Express', 'Chennai', 'Bangalore', 60, 800.00, '2024-01-17')
ON DUPLICATE KEY UPDATE TRAIN_NO=TRAIN_NO;

-- Show table structure
DESCRIBE CUSTOMER;
DESCRIBE ADMIN;
DESCRIBE TRAINS;
DESCRIBE BOOKING_HISTORY;

-- Show sample data
SELECT 'CUSTOMER Table:' as Table_Name;
SELECT * FROM CUSTOMER LIMIT 5;

SELECT 'ADMIN Table:' as Table_Name;
SELECT * FROM ADMIN LIMIT 5;

SELECT 'TRAINS Table:' as Table_Name;
SELECT * FROM TRAINS LIMIT 5; 